apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: weather-app
spec:
  provider:
    vault:
      server: "https://vault-playground.edusuc.net"
      path: "Dev-secret"
      version: "v2"
      auth:
        userPass:
          path: "userpass"
          username: "s12kunballi.wft"
          secretRef:
            name: vault-userpass
            key: password
