apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: kunballi/weather-ui:2add28f131a1f7bb5ee0966e50d985efec7e32f2
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_HOST
              value: auth
            - name: AUTH_PORT
              value: "8080"
            - name: WEATHER_HOST
              value: weather
            - name: WEATHER_PORT
              value: "5000"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: _REDIS_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: weather-app
spec:
  type: NodePort
  selector:
    app: ui
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
